server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  elasticsearch:
    rest:
      #uris: http://192.168.1.200:9200
      uris: http://42.192.128.199:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
