server:
  port: 18083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: gmall_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.200:3306/guli_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  redis:
    #host: 192.168.1.200
    host: 42.192.128.199
    port: 6379
    password: lindonga
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  type-aliases-package: com.atguigu.gmall.sms.entity
  global-config:
    db-config:
      id-type: auto
feign:
  sentinel:
    enabled: true
